stages:
    - build
    - deploy

cache:
    untracked: true

build_libs:
    stage: build
    script:
        - ./autogen.sh
        - ./configure
        - make

create_deb:
    stage: deploy
    only:
        - master
    script:
        - "DEBEMAIL='thomas@kittel.it' dch -v 0.1.`date +%Y%m%d%H%M%S` -D unstable 'New commit'"
        - dpkg-buildpackage -uc -us -tc -rfakeroot
        - reprepro -b ~gitlab-runner/repo include unstable ../*.changes
    when: on_success

