stages:
    - build
    - deploy
    - cleandeploy

build_libs:
    stage: build
    script:
        - ./autogen.sh
        - ./configure
        - make -j 8

create_deb:
    stage: deploy
    only:
        - master
    script:
        - export CURDATE=`date +%Y%m%d%H%M%S`
        - "DEBEMAIL='thomas@kittel.it' dch -v 0.1.$CURDATE -D unstable 'New commit'"
        - dpkg-buildpackage -uc -us -tc -rfakeroot
        - reprepro -b ~gitlab-runner/repo include unstable ../libdwarfparser_0.1.${CURDATE}_amd64.changes
    when: on_success

clean_deb:
    stage: cleandeploy
    only:
        - master
    script:
        - rm -f ../*.deb
        - rm -f ../*.changes
        - rm -f ../*.dsc
        - rm -f ../*.tar.xz
    when: always

